### ISSUE TITLE
probably needs investigation

### ISSUE THREAD

**Issue by mrose17** [dgreif/homebridge-ring-alarm#5] opened 2018-11-07 13:14 UTC
(node:40871) UnhandledPromiseRejectionWarning: Error: Request to ring API at https://app.ring.com/api/v1/rs/connections failed --caused-by-> Request failed with status code 404
        at module.exports (/Users/mrose/Documents/Projects/homespun.io/homebridge-ring-alarm/node_modules/ring-api/propagated-error.js:22:19)
        at ringRequest (/Users/mrose/Documents/Projects/homespun.io/homebridge-ring-alarm/node_modules/ring-api/rest-client.js:78:19)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    (node:40871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
    (node:40871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dgreif** [comment] 2018-11-07 13:18
@mrose17 Thanks for reporting!  I've been hunting this down for the last few days in #2 and I think I finally found the root cause this morning.  Looks like the `connections` endpoint gives a 404 when the base station is doing a firmware update.  I will try to get a fix out today at some point.  Closing this as a duplicate

**Closed by dgreif** 2018-11-07 13:18 UTC

**Comment by mrose17** [comment] 2018-11-07 13:19
many thanks! i couldn't find the linkage myself!
