### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Eli-Liebman** [dgreif/homebridge-ring-alarm#11] opened 2019-01-27 04:43 UTC
When I run `npm i -g homebridge-ring-alarm`, I get the following error:

```
npm ERR! git fetch -a origin (git@github.com:github:dgreif/ring-api) fatal: remote error: 
npm ERR! git fetch -a origin (git@github.com:github:dgreif/ring-api)    is not a valid repository name
npm ERR! git fetch -a origin (git@github.com:github:dgreif/ring-api)   Email support@github.com for help
npm ERR! notarget No compatible version found: ring-api@'github:dgreif/ring-api'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8","2.1.0","2.1.2","2.1.3","3.0.0","3.0.1","3.0.2","3.0.3","3.0.4","3.0.5","3.0.6","3.0.7"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "-g" "homebridge-ring-alarm"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```
I'm on a raspberry pi B+, not sure if that matters. 

Thanks!

**Comment by gadgetfreak98** [comment] 2019-01-27 05:52
I'm also getting errors:

pi@raspberrypi:~ $ sudo npm i homebridge-ring-alarm
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/dgreif/ring-api.git /root/.npm/_cacache/tmp/git-clone-49d34a63/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-49d34a63/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-27T05_51_01_159Z-debug.log

appreciate any help or advice

**Comment by dgreif** [comment] 2019-01-27 05:55
Sorry to hear you guys are having issues. It might be a few days before I
can check it out. I haven’t changed anything in a few weeks so there might
be something odd going on with NPM right now. Will follow up when I have a
chance to test a fresh install.

**Comment by gadgetfreak98** [comment] 2019-01-27 06:31
Much appreciated.  Will be patient in the meantime!

**Comment by Eli-Liebman** [comment] 2019-01-27 15:47
@dgreif - turns out I had a pretty old version of node installed - updating to the latest seemed to solved the install issue for me. 

@gadgetfreak98 maybe give that a try?

**Comment by gadgetfreak98** [comment] 2019-01-27 16:15
Can you tell me what version of node you installed?  When I installed an updated one yesterday, it killed everything else for me, so I went back to 8.15.0.  But maybe I'm missing the steps necessary to bring all the plugins in line with an updated version?  Thanks

**Comment by gadgetfreak98** [comment] 2019-01-27 16:33
did you have to do anything in particular after upgrading to re-enable homebridge and the plugin, or you did it all after node upgrade?

**Comment by Eli-Liebman** [comment] 2019-01-27 16:34
I removed everything using npm uninstall and then uninstall node. Installed the latest and then homebridge

**Comment by gadgetfreak98** [comment] 2019-01-27 16:36
ok, yeah, that may be the way to go... unfortunately as I've messed around quite a bit.  But it seems like it makes sense to have the latest greatest node...

**Comment by gadgetfreak98** [comment] 2019-01-27 16:47
do i need to uninstall all the existing plugins too?

**Comment by Eli-Liebman** [comment] 2019-01-27 20:35
I don't know why you would have to but I can't say for certain.

**Comment by dgreif** [comment] 2019-01-30 19:08
@gadgetfreak98 any updates?

**Comment by gadgetfreak98** [comment] 2019-01-30 19:18
I ended up not doing the Node update from the 8.30 version since it was indicated as being sufficiently high a version and as I was afraid to mess up all the things I had done across half a dozen plugins.  Plus I had basically run out of time.  

Are you still planning to look into potential issues on your end?

**Comment by dgreif** [comment] 2019-01-30 19:31
I think it's specific to your setup so I'm not sure there is much for me to do at this point.  Seems like there are a lot of npm install issues, but they are almost always dependent on the node/npm environment in which you are trying to install it.  Sorry I can't be of more help!

**Comment by gadgetfreak98** [comment] 2019-02-03 06:33
I started anew.  Used a v11 variant of Node, but got the same error code 128.  Rolled back to 10.15 of Node and still got the error.  So no luck.  Any ideas?

**Comment by dgreif** [comment] 2019-02-04 15:23
Going to close this since I am unable to reproduce

**Closed by dgreif** 2019-02-04 15:23 UTC
